# -*- coding: utf-8 -*-
"""clasificaciondefrutas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhklIergdrid5BH1V8_TguPLhXThMpUR
"""

import tensorflow as tf
from tensorflow.keras import layers,models
import matplotlib.pyplot as plt
import numpy as np

#carga del dataset
(x_train,y_train),(x_test,y_test) = tf.keras.datasets.cifar10.load_data()

x_train = x_train/255.0  #normalización de las imagenes para llevarlas a rangos binarios
x_test = x_test/255.0

#definicion del modelo
modelo = models.Sequential([
   layers.Conv2D(32,(3,3), activation = 'relu', input_shape=(32,32,3)), #aplica 32 filtros de 3x3 pixeles sobre la imagen
   layers.MaxPooling2D((2,2)), #resume en un solo valor, toma bloques de 2x2
   layers.Conv2D(64,(3,3), activation ='relu'), #ahora 64 filtros
   layers.MaxPooling2D((2,2)), #reduce el tamaño y se concentra el caracteristicas importantes
   layers.Flatten(), #convierte la imagen en vector unidimensional
   layers.Dense(64, activation='relu'),#primera capa de razonamiento
   layers.Dense(10,activation ='softmax')#igual que la anterior pero con 10 neuronas, es 10 porque corresponde al numero de clases en el dataset
])

#compilación del modelo
modelo.compile(optimizer ='adam',loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

#entrenamiento
history = modelo.fit(x_train, y_train, epochs=10,
                     validation_data = (x_test, y_test))